name: Go

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  releases-matrix:
    name: Compile binaries
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goos: [linux, windows, darwin]
        goarch: ["386", amd64, arm64]
        exclude:  
          - goarch: "386"
            goos: darwin
          - goarch: arm
            goos: darwin
          - goarch: arm
            goos: windows
    steps:
      - uses: actions/checkout@v2
      
      - name: Set BUILD_TIME env
        run: echo BUILD_TIME=$(date -u +%Y%m%d-%H%M) >> ${GITHUB_ENV}
      
      - uses: wangyoucao577/go-release-action@v1.20
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          goos: ${{ matrix.goos }}
          goarch: ${{ matrix.goarch }}
          overwrite: true
          ldflags: -extldflags -static -X github.com/alexsnet/s3sync/util.COMMIT=${{github.sha}} -X github.com/alexsnet/s3sync/util.BUILD_TIME=${{ env.BUILD_TIME }}
          pre_command: export CGO_ENABLED=0
          project_path: "."
          binary_name: "s3sync"
          extra_files: LICENSE README.md
          asset_name: "s3sync-${{ env.BUILD_TIME }}-${{ matrix.goos }}-${{ matrix.goarch }}"